// site/src/lib/demos/cozinha/Ticket.svelte
<script lang="ts">
  import Icon from './Icon.svelte';
  import { WORD, minutes, stopwatch, timing, type Order } from './script';

  // One ticket, after apps/admin/src/features/kitchen/Ticket.tsx: the fuse burning down against the
  // prep time, number and clock big, every item a tap target, one button for the next step and,
  // after "pronto", a few seconds to take it back.
  let {
    order: o,
    sec,
    live,
    bump,
    onToggle,
    onAction,
    onMore,
    onUndo,
  }: {
    order: Order;
    sec: number;
    live: boolean;
    /** seconds left in the "pronto" undo window, while it runs */
    bump: number | undefined;
    onToggle: (itemId: string) => void;
    onAction: () => void;
    onMore: (el: HTMLElement) => void;
    onUndo: () => void;
  } = $props();

  const t = $derived(timing(o, sec));
  const done = $derived(o.items.filter((i) => i.done).length);
  const allDone = $derived(done === o.items.length);
  // the veil covers the button just pressed: the keyboard lands on "desfazer"
  function grab(node: HTMLElement) {
    if (node.closest('article')?.contains(document.activeElement)) node.focus();
  }
  const kind = $derived(o.stage === 'confirmed' ? 'start' : allDone ? 'beckon' : 'quiet');
</script>

<article
  class="ticket {t.urgency}"
  class:arriving={o.arriving}
  aria-label="Pedido {o.number}, {o.name}: {done} de {o.items.length} itens feitos, {WORD[
    t.urgency
  ]}{o.rush ? ', prioridade' : ''}"
>
  <div class="fuse" aria-hidden="true">
    <span style="width: {Math.min(100, Math.max(3, t.ratio * 100))}%"></span>
  </div>

  <header>
    <div class="who">
      <h4 class="num tnum">
        #{o.number}{#if o.rush}<span class="flame"><Icon name="fire" /></span>{/if}
      </h4>
      <p class="mode">
        <Icon name={o.mode === 'delivery' ? 'moped' : 'bag'} />
        <span>{o.mode === 'delivery' ? 'Entrega' : 'Retirada'} · {o.name}</span>
      </p>
    </div>
    <div class="time">
      <p class="face tnum">{stopwatch(t.elapsed)}</p>
      <p class="sub">{t.left < 0 ? `atrasado ${minutes(t.left)}` : `faltam ${minutes(t.left)}`}</p>
    </div>
    {#if o.arriving || o.rush || o.stage === 'confirmed'}
      <p class="tags">
        {#if o.arriving}<span class="tag novo">novo</span>{/if}
        {#if o.rush}<span class="tag rush"><Icon name="fire" /> prioridade</span>{/if}
        {#if o.stage === 'confirmed'}<span class="tag fila">na fila</span>{/if}
      </p>
    {/if}
  </header>

  <ul class="items">
    {#each o.items as i (i.id)}
      <li>
        {#snippet face()}
          <span class="qty tnum" class:many={i.qty > 1}>
            {#if i.done}<Icon name="check" /><span class="sr">feito</span>{:else}{i.qty}×{/if}
          </span>
          <span class="name">{i.done && i.qty > 1 ? `${i.qty}× ` : ''}{i.name}</span>
        {/snippet}
        {#if live}
          <button
            type="button"
            class="item"
            class:done={i.done}
            aria-pressed={i.done}
            onclick={() => onToggle(i.id)}>{@render face()}</button
          >
        {:else}
          <div class="item" class:done={i.done}>{@render face()}</div>
        {/if}
      </li>
    {/each}
  </ul>

  <footer>
    {#if o.items.length > 1 && done}
      <span class="progress tnum" aria-hidden="true">{done}/{o.items.length}</span>
    {/if}
    {#snippet label()}
      <Icon name={o.stage === 'confirmed' ? 'pot' : 'check'} />
      {o.stage === 'confirmed' ? 'começar' : 'pronto'}
    {/snippet}
    {#if live}
      <button type="button" class="act {kind}" onclick={onAction}>{@render label()}</button>
    {:else}
      <div class="act {kind}">{@render label()}</div>
    {/if}
    {#if live}
      <button
        type="button"
        class="more"
        aria-label="mais opções do pedido {o.number}"
        title="mais opções"
        onclick={(e) => onMore(e.currentTarget)}><Icon name="dots" /></button
      >
    {/if}
  </footer>

  {#if bump !== undefined}
    <div class="veil">
      <span class="badge"><Icon name="check" /></span>
      <p class="tnum">#{o.number} pronto</p>
      <button type="button" class="undo" onclick={onUndo} use:grab>
        <Icon name="undo" /> desfazer <span class="tnum">{bump}</span>
      </button>
      <span class="drain" aria-hidden="true"><span></span></span>
    </div>
  {/if}
</article>

<style>
  .ticket {
    container-type: inline-size;
    position: relative;
    display: flex;
    flex-direction: column;
    overflow: hidden;
    border-radius: 0.9em;
    background: var(--surface);
    box-shadow:
      0 0 0 1px var(--line),
      var(--shadow-e1);
  }
  .ticket.warn {
    box-shadow:
      0 0 0 1px color-mix(in srgb, var(--warning) 45%, transparent),
      var(--shadow-e1);
  }
  .ticket.late {
    box-shadow:
      0 0 0 2px var(--danger),
      var(--shadow-e1);
  }
  .fuse {
    height: 0.4em;
    background: var(--surface-sunken);
  }
  .fuse span {
    display: block;
    height: 100%;
    background: var(--success);
    transition: width 1s linear;
  }
  .warn .fuse span {
    background: var(--warning);
  }
  .late .fuse span {
    background: var(--danger);
  }

  header {
    display: grid;
    grid-template-columns: minmax(0, 1fr) auto;
    grid-template-areas: 'who time' 'tags tags';
    gap: 0 0.6em;
    padding: 0.7em 0.85em 0.75em;
  }
  /* a narrow ticket (three across the tablet): the name gets the whole line under the clock */
  @container (max-width: 17em) {
    header {
      grid-template-areas: 'num time' 'mode mode' 'tags tags';
    }
    .who {
      display: contents;
    }
    .num {
      grid-area: num;
      align-self: start;
    }
    .mode {
      grid-area: mode;
    }
  }
  .warn header {
    background: var(--warning-soft);
  }
  .late header {
    background: var(--danger-soft);
  }
  .who {
    grid-area: who;
    min-width: 0;
  }
  .num {
    display: flex;
    align-items: center;
    gap: 0.25em;
    font-family: var(--font-display);
    font-size: 1.75em;
    font-weight: 600;
    line-height: 1;
    letter-spacing: -0.02em;
  }
  .flame {
    color: var(--danger);
    font-size: 0.75em;
    display: inline-flex;
  }
  .mode {
    display: flex;
    align-items: center;
    gap: 0.35em;
    margin-top: 0.35em;
    font-size: 0.85em;
    font-weight: 600;
    line-height: 1.2;
    color: var(--ink-muted);
  }
  .mode span {
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .time {
    grid-area: time;
    text-align: right;
    color: var(--success);
  }
  .warn .time {
    color: var(--warning);
  }
  .late .time {
    color: var(--danger);
  }
  .face {
    font-family: var(--font-display);
    font-size: 1.45em;
    font-weight: 600;
    line-height: 1;
  }
  .sub {
    margin-top: 0.4em;
    font-size: 0.75em;
    font-weight: 600;
    line-height: 1.2;
    white-space: nowrap;
  }
  .tags {
    grid-area: tags;
    display: flex;
    flex-wrap: wrap;
    gap: 0.35em;
    margin-top: 0.55em;
  }
  .tag {
    display: inline-flex;
    align-items: center;
    gap: 0.25em;
    height: 1.9em;
    padding: 0 0.7em;
    border-radius: 999px;
    font-size: 0.75em;
    font-weight: 700;
  }
  .novo {
    background: var(--spark);
    color: var(--on-spark);
  }
  .rush {
    background: var(--danger);
    color: var(--surface);
  }
  .fila {
    background: var(--info-soft);
    color: var(--info);
  }

  .items {
    margin: 0;
    padding: 0;
    list-style: none;
    border-top: 1px solid var(--line);
  }
  .items li + li {
    border-top: 1px solid var(--line);
  }
  .item {
    display: flex;
    align-items: flex-start;
    gap: 0.6em;
    width: 100%;
    min-height: 3.4em;
    padding: 0.55em 0.85em;
    border: 0;
    background: none;
    color: var(--ink);
    font: inherit;
    text-align: left;
  }
  button.item {
    cursor: pointer;
    transition: background var(--duration-instant) var(--ease-soft);
  }
  button.item:hover {
    background: var(--hover);
  }
  button.item:active {
    background: var(--press);
  }
  button:focus-visible {
    outline: 2px solid var(--primary);
    outline-offset: -2px;
    box-shadow: none;
  }
  .qty {
    display: grid;
    place-items: center;
    flex: none;
    min-width: 2.25em;
    height: 2.25em;
    padding: 0 0.3em;
    border-radius: 0.5em;
    background: var(--surface-sunken);
    font-family: var(--font-display);
    font-weight: 700;
    font-size: 1.05em;
  }
  .qty.many {
    background: var(--ink);
    color: var(--surface);
  }
  .done .qty {
    background: var(--success-soft);
    color: var(--success);
    font-size: 1.2em;
  }
  .name {
    min-width: 0;
    padding-top: 0.3em;
    font-weight: 700;
    line-height: 1.25;
  }
  .done .name {
    color: var(--ink-muted);
    text-decoration: line-through 2px;
  }
  .sr {
    position: absolute;
    width: 1px;
    height: 1px;
    overflow: hidden;
    clip-path: inset(50%);
    white-space: nowrap;
  }

  footer {
    display: flex;
    align-items: center;
    gap: 0.45em;
    margin-top: auto;
    padding: 0.6em;
    border-top: 1px solid var(--line);
  }
  .progress {
    padding: 0 0.2em;
    font-size: 0.85em;
    font-weight: 600;
    color: var(--ink-muted);
  }
  .act {
    flex: 1;
    min-width: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.4em;
    height: 3.3em;
    border: 0;
    border-radius: 0.6em;
    font: inherit;
    font-weight: 700;
    font-size: 1em;
  }
  .act :global(.ico) {
    font-size: 1.3em;
  }
  button.act,
  .more {
    cursor: pointer;
  }
  .act.start {
    background: var(--warning-soft);
    color: var(--warning);
  }
  .act.quiet {
    background: var(--surface-sunken);
    color: var(--ink);
    box-shadow: inset 0 0 0 1px var(--line-strong);
  }
  .act.beckon {
    background: var(--spark);
    color: var(--on-spark);
  }
  .more {
    display: grid;
    place-items: center;
    flex: none;
    width: 3.3em;
    height: 3.3em;
    border: 0;
    border-radius: 0.6em;
    background: none;
    color: var(--ink-muted);
    box-shadow: inset 0 0 0 1px var(--line);
    font-size: 1em;
  }
  .more :global(.ico) {
    font-size: 1.4em;
  }
  .more:hover {
    background: var(--hover);
  }

  .veil {
    position: absolute;
    inset: 0;
    z-index: 2;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 0.8em;
    padding: 1em;
    background: var(--spark);
    color: var(--on-spark);
  }
  .badge {
    display: grid;
    place-items: center;
    width: 3.2em;
    height: 3.2em;
    border-radius: 50%;
    background: var(--on-spark);
    color: var(--spark);
    font-size: 1.1em;
  }
  .badge :global(.ico) {
    font-size: 1.7em;
  }
  .veil p {
    font-family: var(--font-display);
    font-size: 1.6em;
    font-weight: 600;
    line-height: 1;
  }
  .undo {
    display: inline-flex;
    align-items: center;
    gap: 0.45em;
    height: 3.3em;
    padding: 0 1.2em;
    border: 0;
    border-radius: 0.6em;
    background: var(--surface);
    color: var(--ink);
    font: inherit;
    font-weight: 700;
    cursor: pointer;
    box-shadow: var(--shadow-e2);
  }
  .undo .tnum {
    color: var(--ink-muted);
  }
  .drain {
    position: absolute;
    inset: auto 0 0;
    height: 0.4em;
    background: color-mix(in srgb, var(--on-spark) 15%, transparent);
  }
  .drain span {
    display: block;
    height: 100%;
    background: var(--on-spark);
    animation: drain 3s linear forwards;
  }
  .arriving {
    animation: drop 420ms var(--ease-soft);
  }
  @keyframes drain {
    from {
      width: 100%;
    }
    to {
      width: 0;
    }
  }
  @keyframes drop {
    from {
      opacity: 0;
      transform: translateY(-0.8em);
    }
  }
  @media (prefers-reduced-motion: reduce) {
    .arriving,
    .drain span {
      animation: none;
    }
    .fuse span {
      transition: none;
    }
  }
</style>

// apps/admin/src/features/kitchen/Ticket.tsx
import {
  ArrowCounterClockwise,
  Bag,
  CalendarBlank,
  Check,
  CookingPot,
  DotsThree,
  HourglassMedium,
  Fire,
  Moped,
  NotePencil,
  Prohibit,
  WarningOctagon,
} from '@phosphor-icons/react';
import { memo, useState, useSyncExternalStore, type ReactNode } from 'react';
import type { KitchenItem, KitchenTicket } from '../../lib/api.ts';
import { cn } from '../../ui/cn.ts';
import {
  actionFor,
  allergySegments,
  isWithout,
  itemMatches,
  itemsFor,
  mentionsAllergy,
  minutes,
  modifierLabel,
  progress,
  stopwatch,
  timing,
  type StationPick,
  type Urgency,
} from './model.ts';

// One shared second for every timer on screen (thirty tickets, one interval).
let second = Date.now();
let ticker: ReturnType<typeof setInterval> | null = null;
const beats = new Set<() => void>();
function onBeat(fn: () => void) {
  beats.add(fn);
  if (!ticker) {
    second = Date.now();
    ticker = setInterval(() => {
      second = Date.now();
      beats.forEach((b) => b());
    }, 1000);
  }
  return () => {
    beats.delete(fn);
    if (!beats.size && ticker) {
      clearInterval(ticker);
      ticker = null;
    }
  };
}
/** now, to the second; `fixed` pins it (the /_ui reference) */
export function useSecond(fixed?: number) {
  const now = useSyncExternalStore(onBeat, () => second);
  return fixed ?? now;
}

// Colour is never the only signal (§4.2): each urgency has a tint, a fuse and a word.
export const URGENCY: Record<
  Urgency,
  { word: string; text: string; band: string; fuse: string; ring: string }
> = {
  fresh: {
    word: 'no tempo',
    text: 'text-success',
    band: '',
    fuse: 'bg-success',
    ring: 'ring-line',
  },
  warn: {
    word: 'atenção',
    text: 'text-warning',
    band: 'bg-warning-soft',
    fuse: 'bg-warning',
    ring: 'ring-warning/45',
  },
  late: {
    word: 'atrasado',
    text: 'text-danger',
    band: 'bg-danger-soft',
    fuse: 'fuse-late',
    ring: 'ring-danger',
  },
  scheduled: {
    word: 'encomenda',
    text: 'text-info',
    band: 'bg-info-soft',
    fuse: 'bg-info',
    ring: 'ring-line',
  },
};

export interface TicketProps {
  ticket: KitchenTicket;
  station: StationPick;
  stationName: (id: string | null) => string;
  /** 1–9: the bump-bar key that selects it */
  slot?: number | undefined;
  selected?: boolean | undefined;
  /** the keyboard's item cursor (index among this station's items) */
  cursor?: number | null | undefined;
  /** just landed: drops in with a lime edge */
  arriving?: boolean | undefined;
  /** "tudo junto" picked a dish: the tickets without it step back */
  focusKey?: string | null | undefined;
  /** bumped, waiting out its undo window until this instant */
  bumpAt?: number | undefined;
  now?: number | undefined;
  onToggle: (t: KitchenTicket, items: KitchenItem[], done: boolean) => void;
  onAction: (t: KitchenTicket) => void;
  onMore: (t: KitchenTicket) => void;
  onUndo: (t: KitchenTicket) => void;
  onSelect?: ((t: KitchenTicket) => void) | undefined;
}

/**
 * A kitchen ticket: the number big enough to read across the pass, a clock that burns down a fuse
 * against the prep time, every item a big tap target (made / not made), what to leave out in red,
 * allergies called out, and one button for the next step.
 */
export const Ticket = memo(function Ticket(p: TicketProps) {
  const { ticket: t, station } = p;
  const now = useSecond(p.now);
  const time = timing(t, now);
  const tone = URGENCY[time.urgency];
  const { mine, others } = itemsFor(t, station);
  const own = progress(mine);
  const action = actionFor(t, station);
  const allergy = mentionsAllergy(t.notes);
  const dimmed = !!p.focusKey && !t.items.some((i) => itemMatches(i, p.focusKey!));
  const waitingOn = [...new Set(others.filter((i) => !i.doneAt).map((i) => i.stationId))];
  const ModeIcon = t.mode === 'delivery' ? Moped : Bag;
  const clockFace = time.urgency === 'scheduled' ? 'hoje' : stopwatch(time.elapsed);
  const sub =
    time.urgency === 'scheduled'
      ? `preparo de ${minutes(t.prepMinutes * 60_000)}`
      : time.left < 0
        ? `atrasado ${minutes(-time.left)}`
        : `faltam ${minutes(time.left)}`;

  return (
    <article
      aria-label={`Pedido ${t.number}${t.name ? `, ${t.name}` : ''}: ${own.done} de ${own.total} itens feitos, ${tone.word}${t.rush ? ', prioridade' : ''}`}
      data-ticket={t.id}
      onPointerDown={() => p.onSelect?.(t)}
      className={cn(
        'relative flex flex-col overflow-hidden rounded-lg bg-surface ring-1 transition-[opacity,scale] duration-200 depth-1',
        tone.ring,
        time.urgency === 'late' && 'ring-2',
        p.selected && 'ring-[3px] ring-spark',
        p.arriving && 'animate-drop-in',
        dimmed && 'scale-[0.98] opacity-35',
      )}
    >
      {/* the fuse: how much of the prep time is gone */}
      <div className="h-2 shrink-0 bg-sunken" aria-hidden>
        <div
          className={cn('h-full transition-[width] duration-1000 ease-linear', tone.fuse)}
          style={{ width: `${Math.min(100, Math.max(3, time.ratio * 100))}%` }}
        />
      </div>

      <header className={cn('px-4 pb-3 pt-3', tone.band)}>
        <div className="flex items-start gap-3">
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2">
              {p.slot ? (
                <kbd
                  className="t-caption grid size-6 shrink-0 place-items-center rounded-[6px] bg-ink font-bold text-surface"
                  aria-hidden
                >
                  {p.slot}
                </kbd>
              ) : null}
              <h3 className="tnum font-display text-[2rem] font-semibold leading-none tracking-tight">
                #{t.number}
              </h3>
              {t.rush ? (
                <Fire weight="fill" className="size-6 shrink-0 text-danger" aria-hidden />
              ) : null}
            </div>
            <p className="t-label mt-1.5 flex min-w-0 items-center gap-1.5 text-muted">
              <ModeIcon weight="bold" className="size-4 shrink-0" aria-hidden />
              <span className="truncate">
                {t.mode === 'delivery' ? 'Entrega' : 'Retirada'}
                {t.name ? ` · ${t.name}` : ''}
              </span>
            </p>
          </div>
          <div className="shrink-0 text-right">
            <p
              className={cn(
                'tnum font-display text-[1.75rem] font-semibold leading-none',
                tone.text,
              )}
            >
              {clockFace}
            </p>
            <p className={cn('t-caption mt-1.5 font-semibold', tone.text)}>{sub}</p>
          </div>
        </div>

        {t.rush || allergy || t.scheduledFor || p.arriving || t.state === 'confirmed' ? (
          <div className="mt-2.5 flex flex-wrap gap-1.5">
            {p.arriving ? <Tag className="bg-spark text-on-spark">novo</Tag> : null}
            {t.rush ? (
              <Tag className="bg-danger text-surface">
                <Fire weight="fill" aria-hidden /> prioridade
              </Tag>
            ) : null}
            {allergy ? (
              <Tag className="bg-surface text-danger ring-2 ring-danger">
                <WarningOctagon weight="fill" aria-hidden /> alergia
              </Tag>
            ) : null}
            {t.scheduledFor ? (
              <Tag className="bg-info-soft text-info">
                <CalendarBlank weight="bold" aria-hidden /> encomenda
              </Tag>
            ) : null}
            {t.state === 'confirmed' ? (
              <Tag className="bg-[var(--st-aceito)] text-[var(--st-aceito-ink)]">na fila</Tag>
            ) : null}
          </div>
        ) : null}
      </header>

      <ul className="flex-1 divide-y divide-line border-t border-line">
        {mine.map((i, k) => (
          <ItemRow
            key={i.id}
            item={i}
            cursor={p.cursor === k}
            focus={!!p.focusKey && itemMatches(i, p.focusKey)}
            onToggle={() => p.onToggle(t, [i], !i.doneAt)}
          />
        ))}
      </ul>

      {others.length ? (
        <p className="t-caption border-t border-dashed border-line px-4 py-2 text-muted">
          +{others.length} {others.length === 1 ? 'item' : 'itens'} em{' '}
          {[...new Set(others.map((i) => p.stationName(i.stationId)))].join(', ')}
          {' · '}
          {progress(others).done === others.length
            ? 'tudo feito'
            : `${progress(others).done} ${progress(others).done === 1 ? 'feito' : 'feitos'}`}
        </p>
      ) : null}

      {t.notes ? (
        <div
          className={cn(
            'mx-3 mb-1 mt-2 flex gap-2 rounded-md px-3 py-2.5',
            allergy ? 'bg-danger-soft ring-1 ring-danger' : 'bg-warning-soft',
          )}
        >
          <NotePencil
            weight="bold"
            className={cn('mt-0.5 size-5 shrink-0', allergy ? 'text-danger' : 'text-warning')}
            aria-hidden
          />
          <p className="t-body min-w-0 whitespace-pre-line break-words font-semibold">
            {allergySegments(t.notes).map((s, k) =>
              s.hit ? (
                <mark key={k} className="rounded bg-danger px-1 text-surface">
                  {s.text}
                </mark>
              ) : (
                <span key={k}>{s.text}</span>
              ),
            )}
          </p>
        </div>
      ) : null}

      <footer className="mt-auto flex items-center gap-2 p-3">
        {own.total > 1 && own.done ? (
          <span className="tnum t-label shrink-0 px-1 text-muted" aria-hidden>
            {own.done}/{own.total}
          </span>
        ) : null}
        {action?.kind === 'wait' ? (
          <p
            role="status"
            className="t-label flex min-h-14 min-w-0 flex-1 items-center gap-2 rounded-md bg-sunken px-3 text-muted"
          >
            <HourglassMedium weight="bold" className="size-6 shrink-0" aria-hidden />
            <span className="min-w-0">
              {action.label}. Falta: {waitingOn.map((s) => p.stationName(s)).join(', ')}
            </span>
          </p>
        ) : action ? (
          <button
            type="button"
            onClick={() => p.onAction(t)}
            className={cn(
              'press t-label flex h-14 min-w-0 flex-1 items-center justify-center gap-2 rounded-md px-3 text-[1.0625rem] font-bold',
              action.kind === 'start'
                ? 'bg-[var(--st-preparando)] text-[var(--st-preparando-ink)]'
                : action.allDone
                  ? 'animate-beckon bg-spark text-on-spark'
                  : // before every item is ticked, "pronto" is there but quiet
                    'bg-sunken text-ink ring-1 ring-line-strong hover:bg-hover',
            )}
          >
            {action.kind === 'start' ? (
              <CookingPot weight="bold" className="size-6" aria-hidden />
            ) : (
              <Check weight="bold" className="size-6" aria-hidden />
            )}
            <span className="truncate">{action.label}</span>
          </button>
        ) : null}
        <button
          type="button"
          aria-label={`mais opções do pedido ${t.number}`}
          title="mais opções"
          onClick={() => p.onMore(t)}
          className="press grid size-14 shrink-0 place-items-center rounded-md text-muted ring-1 ring-line hover:bg-hover"
        >
          <DotsThree weight="bold" className="size-7" />
        </button>
      </footer>

      {p.bumpAt ? <BumpVeil ticket={t} until={p.bumpAt} now={now} onUndo={p.onUndo} /> : null}
    </article>
  );
});

function Tag({ className, children }: { className?: string; children: ReactNode }) {
  return (
    <span
      className={cn(
        't-caption inline-flex h-7 items-center gap-1 rounded-full px-2.5 font-bold [&_svg]:size-4',
        className,
      )}
    >
      {children}
    </span>
  );
}

function ItemRow({
  item: i,
  cursor,
  focus,
  onToggle,
}: {
  item: KitchenItem;
  cursor: boolean;
  focus: boolean;
  onToggle: () => void;
}) {
  const done = !!i.doneAt;
  return (
    <li>
      <button
        type="button"
        aria-pressed={done}
        onClick={onToggle}
        className={cn(
          'press-row flex min-h-14 w-full items-start gap-3 px-4 py-2.5 text-left',
          cursor && 'ring-[3px] ring-inset ring-spark',
          focus && !done && 'bg-spark-soft',
        )}
      >
        <span
          className={cn(
            'tnum grid h-10 min-w-10 shrink-0 place-items-center rounded-sm px-1.5 font-display text-[1.25rem] font-bold',
            done
              ? 'bg-success-soft text-success'
              : i.qty > 1
                ? 'bg-ink text-surface'
                : 'bg-sunken text-ink',
          )}
        >
          {done ? <Check weight="bold" className="size-6" aria-label="feito" /> : `${i.qty}×`}
        </span>
        <span className="min-w-0 flex-1 pt-1">
          <span
            className={cn(
              'block text-[1.125rem] font-bold leading-snug',
              done && 'text-muted line-through decoration-2',
            )}
          >
            {done && i.qty > 1 ? `${i.qty}× ` : ''}
            {i.name}
          </span>
          {i.modifiers.map((m, k) =>
            isWithout(m.name) ? (
              <span
                key={k}
                className={cn(
                  't-body mt-0.5 flex items-center gap-1 font-bold',
                  done ? 'text-muted' : 'text-danger',
                )}
              >
                <Prohibit weight="bold" className="size-4 shrink-0" aria-hidden />
                {modifierLabel(m)}
              </span>
            ) : (
              <span key={k} className="t-body mt-0.5 block text-muted">
                + {modifierLabel(m)}
              </span>
            ),
          )}
          {i.combo.map((c, k) => (
            <span key={k} className="t-body mt-0.5 block text-muted">
              <span className="font-semibold text-ink">{c.slotName}:</span>{' '}
              {c.qty > 1 ? `${c.qty}× ` : ''}
              {c.name}
            </span>
          ))}
        </span>
      </button>
    </li>
  );
}

/** "Pronto" waits a few seconds on the ticket itself, with the undo where the finger is. */
function BumpVeil({
  ticket,
  until,
  now,
  onUndo,
}: {
  ticket: KitchenTicket;
  until: number;
  now: number;
  onUndo: (t: KitchenTicket) => void;
}) {
  const left = Math.max(0, until - now);
  // set once: changing a running animation's duration makes it jump
  const [drain] = useState(() => Math.max(0, until - Date.now()));
  return (
    <div className="animate-fade-up absolute inset-0 z-10 flex flex-col items-center justify-center gap-4 bg-spark p-4 text-on-spark">
      <span className="grid size-16 place-items-center rounded-full bg-on-spark text-spark">
        <Check weight="bold" className="size-9" aria-hidden />
      </span>
      <p className="tnum font-display text-[2rem] font-semibold leading-none">
        #{ticket.number} pronto
      </p>
      <button
        type="button"
        onClick={() => onUndo(ticket)}
        className="press t-label inline-flex h-14 items-center gap-2 rounded-md bg-surface px-6 text-[1.0625rem] font-bold text-ink depth-2"
      >
        <ArrowCounterClockwise weight="bold" className="size-6" aria-hidden />
        desfazer
        <span className="tnum text-muted">{Math.ceil(left / 1000)}</span>
      </button>
      <div className="absolute inset-x-0 bottom-0 h-2 bg-on-spark/15" aria-hidden>
        <div
          className="animate-drain h-full bg-on-spark"
          style={{ animationDuration: `${drain}ms` }}
        />
      </div>
    </div>
  );
}
